### ISSUE TITLE
Add isDebugEnabled() method to logger

### ISSUE THREAD

**Issue by trescube** [pelias/logger#6]
`logger.debug` is being used quite a bit in the API, causing this JSON serialization to always happen:

`logger.debug(JSON.stringify(myObject))`

In a production environment, debug is turned off so a pointless serialization is happening.  By changing this to:

```
if (logger.isDebugEnabled()) {
    logger.debug(JSON.stringify(myObject))
}
```

the serialization will never happen (in production, where it matters).

**Comment by dianashk** [comment]
I believe just throwing objects into the logger.debug function without serializing will do the right thing. It will output the objects in a log-friendly format that's easily parseable by logstash type of tools.

**Comment by dianashk** [comment]
No longer an issue.
